kind: Service
apiVersion: v1
metadata:
  name:  myapp-service
spec:
  type:  NodePort
  selector:
    app:  myapp
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  80
    NodePort:  30001