apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: color-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: color-app
  template:
    metadata:
      labels:
        app: color-app
    spec:
      containers:
      - name: color-app
        image: tpaz1/devopscourse:latest
        ports:
        - containerPort: 8080  # Default port for this app
        env:
        - name: UI_COLOR
          valueFrom:
            configMapKeyRef:
              name: color-config
              key: UI_COLOR
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: color-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: color-app