kind: Service
apiVersion: v1
metadata:
  name: solar-service
spec:
  type: LoadBalancer
  selector:
    app: solar-system
  ports:
  - name: solar-port
    port: 80
    targetPort: 80
    nodePort: 30001
